### ISSUE TITLE
Add one unit test

### ISSUE THREAD

**Issue by vkolova** [vkolova/notum#9]
Add one unit test. Doesn't matter what it's testing.

**Comment by azharakbar** [comment]
@vkolova Ok ... I am on it ... will add a unit test using mocha

**Comment by vkolova** [comment]
@azharakbar ... I meant testing some part of the project..

**Comment by azharakbar** [comment]
ook ... @vkolova

**Comment by SmirnovW** [comment]
@vkolova I suggest a much more pretty framework for testing, it is the jest. Please waiting for my PR ;) I hope you will enjoy it!

**Comment by azharakbar** [comment]
@vkolova 
In /server/api/user.js:131 ... I have an error **Unexpected Token ( **
But when I remove the keyword **async** .. then the error goes away .. and successfully runs

Similar error in /server/api/update.js:24

Also this error occurs due to the presence of **await** keyword in /server/api/update.js:27

The MongoDB connection URI is improper ... in /server/server.js:21
The URI should be of the form 
var connURI = "mongodb://127.0.0.1:27017/"+config.database
mongoose,connect(connURI)

**Comment by azharakbar** [comment]
@vkolova 
Hey, I have added a Unit Test Case For adding new user ... that is .. for the /sign-up api
